### PR TITLE
Fix for the wrong type definition of StepOptions.scrollTo

### LINKED ISSUE #490: Wrong type definition for scrollTo
Hi,

the type definition for `scrollTo` is wrong: https://github.com/shipshapecode/shepherd/blob/master/src/types/step.d.ts#L118

It is defined as boolean, but in reality it accepts  `{ behavior: string, block?: string }|boolean`

### PR DESCRIPTION
**Pull request by moxival**
Simple fix for the wrong type definition of StepOptions.scrollTo property

Fixes #490

### CODE REVIEW

File: src/types/step.d.ts [hunk 1]
```diff
@@ -115,7 +115,7 @@ declare namespace Step {
     /**
      * Should the element be scrolled to when this step is shown?
      */
-    scrollTo?: boolean;
+    scrollTo?: boolean | ScrollIntoViewOptions;
```
Comment (rwwagner90) [inline src/types/step.d.ts]: ScrollIntoViewOptions is not defined. We'll need to add it as well.

Comment (rwwagner90) [reply src/types/step.d.ts]: Looks like this is built into TS, so should be okay.
