### PR TITLE
remove some popper arrow styles and target tippy-arrow

### LINKED ISSUE #266: An in-range update of tippy.js is breaking the build 🚨
## The dependency [tippy.js](https://github.com/atomiks/tippyjs) was updated from `3.0.4` to `3.0.5`.

🚨 [View failing branch](https://github.com/shipshapecode/shepherd/compare/master...shipshapecode:greenkeeper%2Ftippy.js-3.0.5).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

tippy.js is a direct dependency of this project, and **it is very likely causing it to break**. If other packages depend on yours, this update is probably also breaking those in turn.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push:** The Travis CI build failed ([Details](https://travis-ci.org/shipshapecode/shepherd/builds/439447464?utm_source=github_status&utm_medium=notification)).
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 6 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/atomiks/tippyjs/commit/d62cc26a80c3fac426d69f52197d2bfc89483dd4"><code>d62cc26</code></a> <code>3.0.5</code></li>
<li><a href="https://urls.greenkeeper.io/atomiks/tippyjs/commit/27b3313fadb0885251835595bc3209ac84993217"><code>27b3313</code></a> <code>animateFill tweaks</code></li>
<li><a href="https://urls.greenkeeper.io/atomiks/tippyjs/commit/d41bf94e294bb5563f2ade5a11d33bc7372c9427"><code>d41bf94</code></a> <code>animateFill tweaks</code></li>
<li><a href="https://urls.greenkeeper.io/atomiks/tippyjs/commit/e1ffbef0786f4763ba3dbfb7b0ce752c708e73f7"><code>e1ffbef</code></a> <code>Fix followCursor jumpiness with fast transition duration (#315)</code></li>
<li><a href="https://urls.greenkeeper.io/atomiks/tippyjs/commit/d1ba4a46f772a53748c9ac9f871b8593488a557b"><code>d1ba4a4</code></a> <code>add notice to v2 docs about new version</code></li>
<li><a href="https://urls.greenkeeper.io/atomiks/tippyjs/commit/c3cc1188ed9679e0306e18d3ecc574e8d3fa5c11"><code>c3cc118</code></a> <code>quick fixes for old v2 docs</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/atomiks/tippyjs/compare/7550cd222d1e0e746a0fb5c4e9a73a0d866faf51...d62cc26a80c3fac426d69f52197d2bfc89483dd4">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by chuckcarpenter**
Fixes #266

### CODE REVIEW

File: src/js/utils/tooltip-defaults.js [hunk 1]
```diff
@@ -1,5 +1,7 @@
 export const defaults = {
   trigger: 'manual',
+  arrow: true,
```
Comment (chuckcarpenter) [inline src/js/utils/tooltip-defaults.js]: @BrianSipple this is the config change and then we just remove popper arrow stuff. @rwwagner90 I do believe that theming is affected, but perhaps easier in Tippy?

https://atomiks.github.io/tippyjs//#creating-custom-themes-creating-a-theme

Comment (BrianSipple) [reply src/js/utils/tooltip-defaults.js]: @chuckcarpenter @rwwagner90 Agreed that Tippy offers plenty of potential for better themeing. My impression is that we planning that as [part of 3.0](https://github.com/shipshapecode/shepherd/projects/4)

File: docs/welcome/js/welcome.js [hunk 2]
```diff
@@ -31,7 +31,7 @@
           as they enter and exit the view.
         `
       ],
-      attachTo: '.hero-welcome bottom',
+      attachTo: '.hero-welcome bottom-start',
```
Comment (BrianSipple) [inline docs/welcome/js/welcome.js]: @chuckcarpenter I'm seeing a few issues in the demo app:

screen shot 2018-10-10 at 2 16 09 pm

Did you mean to add the `-start` here?

Comment (BrianSipple) [reply docs/welcome/js/welcome.js]: Also, I think we still need to add calculations for `-start` and `-end`.

Comment (BrianSipple) [reply docs/welcome/js/welcome.js]: @chuckcarpenter @rwwagner90 Perhaps it would be best to simply _add_ to our existing Popper arrow styles for now (i.e., adding calculations for the `-start` and `-end` positions). 

We could make fully converting to Tippy arrows a part of 2.X or 3.0.

Comment (rwwagner90) [reply docs/welcome/js/welcome.js]: @BrianSipple I'm okay with either, but it might be simpler to fully convert to tippy arrows now, rather than trying to use the old styles. I'll leave it up to you guys 😃

File: src/js/utils/tooltip-defaults.js (hunk 1 above)
Comment (chuckcarpenter) [reply src/js/utils/tooltip-defaults.js]: agree, but I think setting this to the default arrow is definitely for now.

File: docs/welcome/js/welcome.js (hunk 2 above)
Comment (chuckcarpenter) [reply docs/welcome/js/welcome.js]: @BrianSipple I think this is easier than adding the additional calculations though? This is a setting and falls back to Tippy options.

**Comment by chuckcarpenter** [comment]
@BrianSipple Ch ch changes...

File: docs/welcome/js/welcome.js (hunk 2 above)
Comment (BrianSipple) [reply docs/welcome/js/welcome.js]: Adding the additional calculations would mean we don't risk breaking things like the positioning of the main content and aesthetic appearance of the arrows. Ultimately, using Tippy directly would be cleaner, but I feel like we'd be better off focusing on that after shipping 2.0.

Comment (BrianSipple) [reply docs/welcome/js/welcome.js]: @chuckcarpenter @rwwagner90 Setting the position to `bottom-start` still produces the screenshot above.

Comment (BrianSipple) [reply docs/welcome/js/welcome.js]: @chuckcarpenter @rwwagner90 This could be what we want, though. I was thinking the placement should move the arrow, but after revisiting both the Tippy and Popper demos, it appears that the main idea is to move the body of the tooltip.

**Comment by BrianSipple** [comment]
I'm good with this if I'm right that I was wrong [here](https://github.com/shipshapecode/shepherd/pull/268#discussion_r224288672)

**Comment by rwwagner90** [comment]
@BrianSipple your link isn't linking to what you were wrong about for me. Can you elaborate? If you and @chuckcarpenter agree that this is ready, one of you can feel free to merge. We should quickly follow up with extensive arrow and theming refactors though, probably.

**Comment by BrianSipple** [comment]
@rwwagner90 It's the discussion where I requested changes. I thought that the styling of the tooltip was an issue -- but maybe it's not.

**Comment by rwwagner90** [comment]
@BrianSipple yeah that link still doesn't work. Perhaps a bug in GitHub, but it doesn't show the comment. 

@BrianSipple @chuckcarpenter Just to reiterate, if you guys both agree this is good to go, feel free to merge. I just want to make sure that immediately after this we switch to using tippy arrows and themes directly, instead of doing a bunch of custom styles.

**Comment by chuckcarpenter** [comment]
I think it's ready, then we can iterate further. Do you agree @BrianSipple ?
